### ISSUE TITLE
Choice of either TO or TV on MTurk Hits page

### ISSUE THREAD

**Issue by kimadagem** [brandonhellman/mturk-suite#182]
I see the separate places to choose them in Options but I can't see TO at all if TV is checked. If I uncheck it then TO - both sites - shows up again. Basically, it's the same issue that I had last week; the settings are just a bit different.

I'm not sure this is related but - I'm wondering now whether I should get an API key; if I do, and enter it on MTS, will that remove my ability to see TO reviews? I prefer TO to TV and if I had a choice between them I would pick TO; for the few times I need to check TV I think could do that manually by opening a page. (I realize that's not your area; I'm just wondering how MTS will handle the lack of an API key.)

**Comment by brandonhellman** [comment]
In HIT finder I messed something up so disabling TO/TV in the options will disable the wrong one in HF. It should work correctly on the actual MTurk page. The goal is for them to work completely independently, but lots of issues are popping up while they are getting split up, sorry. 

Having an API key for Turkerview won't affect TO in anyway.

**Comment by chrisinit** [comment]
This should be fixed on pull. @kimadagem since you already have a TV account it's probably better to just grab your API key. It's free, and the features that are free will keep working and the ones that aren't will simply go away. MTS wont nag you about subscribing to TV, so you'll get the free stuff forever and the other stuff should just hide itself silently.

Either way the swap should be fixed next update & you can leave TV disabled then.

**Comment by kimadagem** [comment]
Update on this - it's still happening on the MTurk page (not on Hit Finder). I got the API key, plugged it in, and checked TV, but when I first opened the MTurk Hits page the only reviews I could see were TV's; I had to turn it off in Settings to see TO.

**Comment by brandonhellman** [comment]
This should be because of the TO servers being slow to respond and nothing to do with the settings anymore.
