### ISSUE TITLE
Once / Panda buttons gone on HIT preview page v 2.1.10

### ISSUE THREAD

**Issue by mrzoink** [brandonhellman/mturk-suite#29]
I'm not seeing any PandA options on hit previews.

I didn't see the previous bug, but I'm being affected now.

Chrome OS / Chrome 63.0.3239.140 (Official Build) (64-bit)

**Comment by bmcg2201** [comment]
I was affected by the previous bug, and just had this one start up again.  

Chrome - Version 63.0.3239.132 (Official Build) (64-bit)

edit: and its working again 5 minutes after I posted, weird.

**Comment by mrzoink** [comment]
Mine just started working too.

**Comment by brandonhellman** [comment]
Fixed

**Comment by mrzoink** [comment]
This issue is still cropping up, but I noticed a behavior I hadn't thought of before - I logged out and back into mturk and that seemed to resolve the issue.
